/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sokoban_utils_WindowsFileChooser */

#ifndef _Included_com_sokoban_utils_WindowsFileChooser
#define _Included_com_sokoban_utils_WindowsFileChooser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sokoban_utils_WindowsFileChooser
 * Method:    openFileChooser
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sokoban_utils_WindowsFileChooser_openFileChooser
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sokoban_utils_WindowsFileChooser
 * Method:    saveFileChooser
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sokoban_utils_WindowsFileChooser_saveFileChooser
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
